CREATE TABLE IF NOT EXISTS ServerConfig (
  `Name` VARCHAR(64) NOT NULL,
  `Tag` VARCHAR(16) NOT NULL,
  `Developer` VARCHAR(64) NOT NULL,
  `MaxWealth` INT DEFAULT 0,
  `MaxGold` INT DEFAULT 0,
  `MaxDiamond` INT DEFAULT 0,
  `TotalWealth` INT DEFAULT 0,
  `TotalGold` INT DEFAULT 0,
  `TotalDiamond` INT DEFAULT 0
);


CREATE TABLE IF NOT EXISTS MasterData (
  `MasterID` INT AUTO_INCREMENT PRIMARY KEY,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `Alias1` VARCHAR(24) DEFAULT NULL,
  `Alias2` VARCHAR(24) DEFAULT NULL,
  `Alias3` VARCHAR(24) DEFAULT NULL
);

-- Create table PlayerData
CREATE TABLE IF NOT EXISTS PlayerData (
  `PlayerID` INT AUTO_INCREMENT PRIMARY KEY,
  `MasterID` INT NOT NULL,
  `Name` VARCHAR(24) NOT NULL,
  `Registered` INT(1) DEFAULT 0,
  `Code` INT(4) NOT NULL,
  `Skin` INT DEFAULT 0,
  `Gender` INT(1) DEFAULT 0,
  `Age` INT(100) DEFAULT 0,
  `Health` INT DEFAULT 100,
  `Armor` INT DEFAULT 100,
  `Hunger` INT DEFAULT 100,
  `Thirst` INT DEFAULT 100,
  `PosX` FLOAT DEFAULT 0.0,
  `PosY` FLOAT DEFAULT 0.0,
  `PosZ` FLOAT DEFAULT 0.0,
  `PosA` FLOAT DEFAULT 0.0,
  `Admin` INT(1) DEFAULT 0,
  `AdminLevel` INT(1) DEFAULT 0,
  `AdminName` VARCHAR(24) DEFAULT NULL,
  `Banned` INT(1) DEFAULT 0,
  `BanReason` VARCHAR(255) DEFAULT NULL,
  `LastLogin` INT DEFAULT 0,
  `LastLogout` INT DEFAULT 0,
  `LastIP` VARCHAR(15) DEFAULT NULL,
  `LastDevice` INT DEFAULT 0,

  FOREIGN KEY (`MasterID`) REFERENCES MasterData(`MasterID`) ON DELETE CASCADE
);


