CREATE TABLE IF NOT EXISTS MasterData (
  `MasterID` INT AUTO_INCREMENT PRIMARY KEY,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `Alias1` VARCHAR(24) DEFAULT NULL,
  `Alias2` VARCHAR(24) DEFAULT NULL,
  `Alias3` VARCHAR(24) DEFAULT NULL
);

-- Create table PlayerData
CREATE TABLE IF NOT EXISTS PlayerData (
  `PlayerID` INT AUTO_INCREMENT PRIMARY KEY,
  `MasterID` INT NOT NULL,
  `Name` VARCHAR(24) NOT NULL,
  `Registered` INT(1) DEFAULT 0,
  `Code` INT(4) NOT NULL,
  `Skin` INT DEFAULT 0,
  `Gender` INT(1) DEFAULT 0,
  `Age` INT(100) DEFAULT 0,
  `Health` INT DEFAULT 100,
  `Armor` INT DEFAULT 100,
  `Hunger` INT DEFAULT 100,
  `Thirst` INT DEFAULT 100,
  `PosX` FLOAT DEFAULT 0.0,
  `PosY` FLOAT DEFAULT 0.0,
  `PosZ` FLOAT DEFAULT 0.0,
  `PosA` FLOAT DEFAULT 0.0,
  FOREIGN KEY (`MasterID`) REFERENCES MasterData(`MasterID`) ON DELETE CASCADE
);

-- Create table TrustedDevices
CREATE TABLE IF NOT EXISTS TrustedDevices (
  `TrustedID` INT AUTO_INCREMENT PRIMARY KEY,
  `MasterID` INT NOT NULL,
  `DeviceHash` VARCHAR(128) NOT NULL,
  `LastUsedIP` VARCHAR(45) NOT NULL,
  `AddedTimestamp` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`MasterID`) REFERENCES MasterData(`MasterID`) ON DELETE CASCADE
);

-- Create Table Job
CREATE TABLE IF NOT EXISTS Jobs (
  `JobID` INT AUTO_INCREMENT PRIMARY KEY,
  `JobName` VARCHAR(64) NOT NULL,
  `JobOwner` VARCHAR(24) NOT NULL,
  `JobOwnerID` INT DEFAULT 0,
  `JobType` INT DEFAULT 0,
  `JobSalary` INT DEFAULT 0,
  `JobExists` INT DEFAULT 0,
  `JobPosX` FLOAT DEFAULT 0.0,
  `JobPosY` FLOAT DEFAULT 0.0,
  `JobPosZ` FLOAT DEFAULT 0.0,
  `JobSkin` INT DEFAULT 0
);